name: riskprediction
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/intl_en.json
    - assets/lang/intl_ru.json
    - assets/lang/intl_vi.json
    - assets/lang/intl_fr.json
    - assets/lang/intl_de.json
    - assets/lang/intl_zh.json
    - assets/lang/intl_es.json
    - assets/lang/intl_ar.json
  fonts:
    - family: League Spartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LeagueSpartan-Black.ttf
          weight: 900
