final Map<String, Map<String, List<String>>> faqKeywords = {
  "vi": {
    "Chào" : ["Hi", "hi", "hello", "xin chào", "chào", "Hế lô", "alo", "Alo"],
    "Đăng ký tài khoản mới": ["đăng ký", "tài khoản mới", "tạo tài khoản"],
    "Quên mật khẩu": ["quên mật khẩu", "khôi phục mật khẩu", "lấy lại mật khẩu"],
    "Thay đổi mật khẩu": ["đổi mật khẩu", "thay đổi mật khẩu"],
    "Sử dụng tài khoản trên nhiều thiết bị": ["nhiều thiết bị", "sử dụng trên thiết bị khác"],
    "Không nhận được mã xác thực": ["mã xác thực", "không nhận được mã", "xác thực"],
    "Xoá tài khoản": ["xoá tài khoản", "xóa"],
    "Cập nhật thông tin cá nhân": ["cập nhật thông tin", "chỉnh sửa thông tin", "thay đổi thông tin"],
    "Không thể đăng nhập vào tài khoản": ["không đăng nhập được", "lỗi đăng nhập", "đăng nhập thất bại"],
    "Đăng nhập bằng mạng xã hội": ["mạng xã hội", "google", "facebook", "đăng nhập"],
    "Tài khoản bị khóa": ["bị khóa tài khoản", "mở khóa", "tài khoản bị chặn"],
    "Tạo báo cáo rủi ro": ["tạo báo cáo", "báo cáo rủi ro", "tạo mới"],
    "Chụp ảnh hoặc quay video khi tạo báo cáo": ["chụp ảnh", "quay video", "báo cáo"],
    "Chỉnh sửa báo cáo đã gửi": ["chỉnh sửa báo cáo", "cập nhật báo cáo"],
    "Báo cáo rủi ro gửi đến đâu": ["bộ phận xử lý", "gửi đến đâu", "phòng ban"],
    "Báo cáo rủi ro ẩn danh": ["ẩn danh", "không tiết lộ danh tính"],
    "Phân loại mức độ nguy hiểm": ["mức độ nguy hiểm", "phân loại rủi ro"],
    "Xem lại các báo cáo đã gửi": ["lịch sử báo cáo", "báo cáo đã gửi"],
    "Cập nhật trạng thái của báo cáo": ["cập nhật trạng thái", "trạng thái báo cáo"],
    "Giới hạn số lượng báo cáo": ["giới hạn báo cáo", "tạo báo cáo nhiều lần"],
    "Thông báo khi xử lý báo cáo": ["thông báo xử lý", "báo cáo được xử lý"],
    "Tích lũy điểm thưởng": ["điểm thưởng", "tích điểm", "phần thưởng"],
    "Đổi điểm thưởng": ["đổi điểm", "sử dụng điểm", "quà tặng"],
    "Kiểm tra điểm thưởng đã nhận": ["kiểm tra điểm", "xem điểm thưởng"],
    "Thời hạn sử dụng điểm thưởng": ["hạn sử dụng điểm", "thời gian sử dụng"],
    "Chuyển điểm thưởng cho người khác": ["chuyển điểm", "tặng điểm"],
    "Hành động nhận điểm thưởng": ["hành động tích điểm", "cách nhận điểm"],
    "Tham gia sự kiện và nhận điểm thưởng": ["tham gia sự kiện", "sự kiện tích điểm"],
    "Mất điểm nếu báo cáo bị từ chối": ["mất điểm", "báo cáo bị từ chối"],
    "Điểm thưởng ảnh hưởng cấp bậc": ["cấp bậc", "thăng hạng", "điểm thưởng"],
    "Lịch sử điểm thưởng": ["lịch sử điểm", "xem lịch sử"],
    "Bảo mật dữ liệu người dùng": ["bảo mật", "an toàn dữ liệu"],
    "Giữ an toàn tài khoản": ["bảo vệ tài khoản", "bảo mật tài khoản"],
    "Thông tin cá nhân chia sẻ với bên thứ ba": ["chia sẻ thông tin", "bên thứ ba"],
    "Kiểm soát ai xem báo cáo": ["ai xem báo cáo", "ẩn báo cáo"],
    "Báo cáo vấn đề bảo mật": ["vấn đề bảo mật", "lỗi bảo mật"],
    "Yêu cầu quyền truy cập máy ảnh và vị trí": ["quyền truy cập", "máy ảnh", "vị trí"],
    "Xoá dữ liệu cá nhân": ["xóa dữ liệu", "xoá thông tin"],
    "Sử dụng dữ liệu cho quảng cáo": ["quảng cáo", "dữ liệu cá nhân"],
    "Người khác xem báo cáo của tôi": ["ai xem báo cáo", "quyền xem báo cáo"],
    "Bảo mật hai lớp": ["xác thực hai lớp", "bảo mật hai lớp"],
    "Liên hệ hỗ trợ khách hàng": ["liên hệ hỗ trợ", "hỗ trợ khách hàng"],
    "Gửi ý kiến đóng góp": ["góp ý", "phản hồi"],
    "Báo cáo lỗi ứng dụng": ["báo cáo lỗi", "lỗi ứng dụng"],
    "Nâng cấp ứng dụng": ["nâng cấp", "cập nhật ứng dụng"],
    "Thời gian phản hồi yêu cầu": ["thời gian phản hồi", "phản hồi hỗ trợ"],
    "Yêu cầu tính năng mới": ["tính năng mới", "gợi ý tính năng"],
    "Truy cập tài liệu hướng dẫn": ["hướng dẫn sử dụng", "tài liệu"],
    "Ứng dụng có sẵn trên hệ điều hành khác": ["nền tảng khác", "hệ điều hành"],
    "Thử nghiệm tính năng mới": ["thử nghiệm", "beta"],
  },
  "en": {
    "Greeting" : ["Hi", "Hello", "hi", "hello", "morning", "alo"],
    "Register a new account": ["register", "new account", "create account"],
    "Forgot password": ["forgot password", "reset password", "retrieve password"],
    "Change password": ["change password", "update password"],
    "Use account on multiple devices": ["multiple devices", "different devices", "use on other devices"],
    "Did not receive verification code": ["verification code", "did not receive code", "authentication code"],
    "Delete account": ["delete account", "remove account"],
    "Update personal information": ["update info", "edit personal info", "change information"],
    "Cannot log in to my account": ["cannot log in", "login error", "login failed"],
    "Log in using social media": ["social media", "google", "facebook", "login"],
    "Account locked": ["account locked", "unlock account", "suspended account"],
    "Create a risk report": ["create report", "risk report", "new report"],
    "Take photo or video when creating report": ["take photo", "record video", "create report"],
    "Edit a submitted report": ["edit report", "update report"],
    "Where is the risk report sent": ["sent to", "report destination", "department handling"],
    "Submit anonymous risk report": ["anonymous", "hide identity", "anonymous report"],
    "Classify risk severity levels": ["risk severity", "classify risks"],
    "View submitted reports": ["view reports", "report history", "previous reports"],
    "Update report status": ["update status", "report status"],
    "Limit on number of reports": ["limit reports", "number of reports", "how many reports"],
    "Notifications when report processed": ["notifications", "report processed", "updates"],
    "Accumulate reward points": ["reward points", "earn points", "collect rewards"],
    "Redeem reward points": ["redeem points", "use points", "rewards"],
    "Check received reward points": ["check points", "view rewards"],
    "Reward points expiration": ["points expiration", "expiry date"],
    "Transfer reward points to others": ["transfer points", "give points", "send points"],
    "Actions to earn reward points": ["earn points", "actions for rewards"],
    "Join events to earn points": ["join events", "event rewards"],
    "Lose points if report rejected": ["lose points", "report rejected"],
    "Reward points affect rank": ["rank", "level", "promotion points"],
    "Reward points history": ["points history", "reward history"],
    "User data security": ["data security", "privacy"],
    "Keep my account safe": ["account safety", "protect account"],
    "Personal data shared with third parties": ["data sharing", "third parties"],
    "Control who views my reports": ["who can view", "report visibility"],
    "Report security issues": ["report issues", "security issues"],
    "App requesting camera and location access": ["camera access", "location access", "permissions"],
    "Request to delete personal data": ["delete data", "remove data"],
    "Use my data for advertising": ["advertising", "data usage"],
    "Others viewing my reports": ["view reports", "who can see reports"],
    "Enable two-factor authentication": ["two-factor", "two-step verification"],
    "Contact customer support": ["contact support", "customer service"],
    "Send feedback about the app": ["feedback", "app feedback"],
    "Report app issues": ["report issues", "app bugs", "errors"],
    "Upgrade the app": ["upgrade app", "update app"],
    "Time for support to respond": ["support response time", "how long support"],
    "Request new features": ["new features", "feature request"],
    "Access usage guide": ["guide", "help documents"],
    "App available on other platforms": ["other platforms", "operating systems"],
    "Test new features": ["test features", "beta program"],
  },
  "ru": {
    "Привет": ["Привет", "привет", "добрый"],
    "Регистрация нового аккаунта": ["регистрация", "новый аккаунт", "создать аккаунт"],
    "Забыл пароль": ["забыли пароль", "восстановить пароль", "сброс пароля"],
    "Изменить пароль": ["изменить пароль", "обновить пароль", "сменить пароль"],
    "Использовать аккаунт на нескольких устройствах": ["несколько устройств", "другие устройства", "использовать на устройствах"],
    "Не получил код подтверждения": ["код подтверждения", "не получил код", "код аутентификации"],
    "Удалить аккаунт": ["удалить аккаунт", "удаление аккаунта"],
    "Обновить личную информацию": ["обновить информацию", "редактировать личные данные", "изменить информацию"],
    "Не могу войти в аккаунт": ["не могу войти", "ошибка входа", "не получается войти"],
    "Вход через соцсети": ["соцсети", "google", "facebook", "вход через"],
    "Аккаунт заблокирован": ["аккаунт заблокирован", "разблокировать аккаунт", "аккаунт приостановлен"],
    "Создать отчет о риске": ["создать отчет", "отчет о риске", "новый отчет"],
    "Сделать фото или видео для отчета": ["сделать фото", "записать видео", "отчет"],
    "Редактировать отправленный отчет": ["редактировать отчет", "обновить отчет"],
    "Куда отправляется отчет о риске": ["куда отправляется", "отчет отправить", "кому направить"],
    "Отчет о риске анонимно": ["анонимно", "скрыть личность", "анонимный отчет"],
    "Классификация уровней риска": ["уровень риска", "классификация рисков"],
    "Просмотр отправленных отчетов": ["просмотр отчетов", "история отчетов", "прошлые отчеты"],
    "Обновить статус отчета": ["обновить статус", "статус отчета"],
    "Лимит количества отчетов": ["лимит отчетов", "сколько отчетов", "ограничение"],
    "Уведомления об обработке отчета": ["уведомления", "отчет обработан", "обновления"],
    "Накопить бонусные баллы": ["бонусные баллы", "заработать баллы", "собирать награды"],
    "Обменять бонусные баллы": ["обмен баллов", "использовать баллы", "награды"],
    "Проверить полученные бонусы": ["проверить баллы", "посмотреть бонусы"],
    "Срок действия бонусных баллов": ["срок действия", "срок баллов"],
    "Передать бонусные баллы другим": ["передать баллы", "подарить баллы"],
    "Действия для получения баллов": ["действия для баллов", "как получить баллы"],
    "Участвовать в событиях для получения баллов": ["участвовать в событиях", "события для баллов"],
    "Потеря баллов, если отчет отклонен": ["потеря баллов", "отчет отклонен"],
    "Бонусные баллы влияют на уровень": ["уровень", "повышение", "баллы"],
    "История бонусных баллов": ["история баллов", "посмотреть историю"],
    "Безопасность данных пользователя": ["безопасность данных", "конфиденциальность"],
    "Защита аккаунта": ["защита аккаунта", "безопасность аккаунта"],
    "Личные данные передаются третьим лицам": ["данные передаются", "третьи лица"],
    "Кто может просматривать мои отчеты": ["кто видит отчеты", "доступ к отчетам"],
    "Сообщить о проблемах с безопасностью": ["проблемы с безопасностью", "сообщить о проблеме"],
    "Почему приложению нужен доступ к камере и местоположению": ["доступ к камере", "доступ к местоположению", "разрешения"],
    "Удалить личные данные": ["удалить данные", "удаление данных"],
    "Используются ли мои данные для рекламы": ["реклама", "использование данных"],
    "Кто может видеть мои отчеты": ["кто видит отчеты", "доступ к отчетам"],
    "Включить двухфакторную аутентификацию": ["двухфакторная аутентификация", "двухэтапная проверка"],
    "Связаться с клиентской поддержкой": ["связаться с поддержкой", "клиентская поддержка"],
    "Отправить отзыв о приложении": ["отзыв", "обратная связь"],
    "Сообщить об ошибке приложения": ["сообщить об ошибке", "ошибки приложения"],
    "Обновить приложение": ["обновить приложение", "обновление"],
    "Время ответа поддержки": ["время ответа", "поддержка отвечает"],
    "Запросить новые функции": ["новые функции", "запрос функции"],
    "Получить руководство по использованию": ["руководство", "документы помощи"],
    "Приложение доступно на других платформах": ["другие платформы", "операционные системы"],
    "Тестировать новые функции": ["тестирование", "бета-версия"],
  },
};

final Map<String, Map<String, String>> faqData = {
  "vi": {
    "Chào" : "Xin chào, mình có thể giúp gì cho bạn ?",
    "Đăng ký tài khoản mới" : "Để đăng ký tài khoản mới, hãy mở ứng dụng và chọn 'Đăng ký'. Sau đó, điền thông tin cá nhân và làm theo các bước hướng dẫn.",
    "Quên mật khẩu": "Hãy nhấp vào 'Quên mật khẩu' trên trang đăng nhập và nhập email của bạn. Một liên kết để đặt lại mật khẩu sẽ được gửi đến email của bạn.",
    "Thay đổi mật khẩu": "Vào phần 'Cài đặt tài khoản' và chọn 'Đổi mật khẩu'. Nhập mật khẩu hiện tại và mật khẩu mới, sau đó xác nhận thay đổi.",
    "Sử dụng tài khoản trên nhiều thiết bị": "Có, bạn có thể sử dụng tài khoản của mình trên nhiều thiết bị miễn là bạn đăng nhập bằng cùng một tài khoản.",
    "Không nhận được mã xác thực": "Đảm bảo rằng bạn đã nhập đúng số điện thoại hoặc email. Nếu vấn đề vẫn tiếp diễn, hãy kiểm tra kết nối mạng và thử lại.",
    "Xoá tài khoản": "Vào 'Cài đặt tài khoản' và chọn 'Xoá tài khoản'. Lưu ý rằng thao tác này là không thể hoàn tác và sẽ xoá toàn bộ dữ liệu của bạn.",
    "Cập nhật thông tin cá nhân": "Vào 'Cài đặt tài khoản' và chọn 'Chỉnh sửa thông tin cá nhân'. Bạn có thể cập nhật các thông tin như tên, email và số điện thoại.",
    "Không thể đăng nhập vào tài khoản": "Kiểm tra xem bạn đã nhập đúng thông tin đăng nhập chưa. Nếu vẫn không được, thử đặt lại mật khẩu hoặc liên hệ bộ phận hỗ trợ.",
    "Đăng nhập bằng mạng xã hội": "Có, bạn có thể đăng nhập bằng tài khoản Google hoặc Facebook nếu ứng dụng hỗ trợ.",
    "Tài khoản bị khóa": "Vui lòng liên hệ với bộ phận hỗ trợ khách hàng để biết thêm chi tiết và yêu cầu mở khóa tài khoản.",
    "Tạo báo cáo rủi ro": "Chọn 'Tạo báo cáo' trong menu chính, sau đó làm theo các bước để nhập thông tin và thêm hình ảnh (nếu cần).",
    "Chụp ảnh hoặc quay video khi tạo báo cáo": "Có, ứng dụng cho phép bạn chụp ảnh và quay video để minh họa tình trạng rủi ro.",
    "Chỉnh sửa báo cáo đã gửi": "Sau khi gửi báo cáo, bạn không thể chỉnh sửa. Tuy nhiên, bạn có thể tạo một báo cáo mới nếu cần cập nhật thông tin.",
    "Báo cáo rủi ro gửi đến đâu": "Báo cáo sẽ được tự động gửi đến bộ phận liên quan dựa trên nội dung và mức độ nghiêm trọng của rủi ro.",
    "Báo cáo rủi ro ẩn danh": "Có, bạn có thể chọn chế độ ẩn danh khi tạo báo cáo nếu không muốn tiết lộ danh tính.",
    "Phân loại mức độ nguy hiểm": "Ứng dụng sẽ cung cấp các tùy chọn phân loại rủi ro dựa trên tiêu chuẩn an toàn của doanh nghiệp.",
    "Xem lại các báo cáo đã gửi": "Vào 'Lịch sử báo cáo' để xem lại các báo cáo bạn đã gửi.",
    "Cập nhật trạng thái của báo cáo": "Sau khi gửi báo cáo, bạn sẽ nhận được thông báo khi trạng thái của báo cáo thay đổi.",
    "Giới hạn số lượng báo cáo": "Không có giới hạn về số lượng báo cáo bạn có thể gửi.",
    "Thông báo khi xử lý báo cáo": "Có, bạn sẽ nhận được thông báo khi báo cáo của bạn được xem xét và xử lý.",
    "Tích lũy điểm thưởng": "Bạn có thể tích lũy điểm thưởng bằng cách tạo báo cáo rủi ro, đóng góp ý kiến và tham gia các hoạt động của ứng dụng.",
    "Đổi điểm thưởng": "Điểm thưởng có thể được đổi lấy các phần quà hoặc ưu đãi khác nhau, tùy thuộc vào chương trình hiện hành.",
    "Kiểm tra điểm thưởng đã nhận": "Điểm thưởng sẽ hiển thị trên hồ sơ của bạn và bạn sẽ nhận được thông báo mỗi khi được tích lũy điểm.",
    "Thời hạn sử dụng điểm thưởng": "Có, một số điểm thưởng có thể có thời hạn. Kiểm tra trong phần 'Điểm thưởng' để biết chi tiết.",
    "Chuyển điểm thưởng cho người khác": "Hiện tại, điểm thưởng không thể chuyển nhượng.",
    "Hành động nhận điểm thưởng": "Bạn sẽ nhận được điểm khi tạo báo cáo, đóng góp ý kiến, và tham gia các hoạt động sự kiện.",
    "Tham gia sự kiện và nhận điểm thưởng": "Kiểm tra phần 'Sự kiện' trong ứng dụng để biết các chương trình khuyến mãi và cách tham gia.",
    "Mất điểm nếu báo cáo bị từ chối": "Không, bạn sẽ không mất điểm nếu báo cáo bị từ chối.",
    "Điểm thưởng ảnh hưởng cấp bậc": "Có, số điểm tích lũy có thể ảnh hưởng đến cấp bậc và ưu đãi trong ứng dụng.",
    "Lịch sử điểm thưởng": "Vào phần 'Điểm thưởng' trong hồ sơ của bạn để xem lịch sử.",
    "Bảo mật dữ liệu người dùng": "Có, ứng dụng sử dụng các biện pháp bảo mật hiện đại để bảo vệ dữ liệu người dùng.",
    "Giữ an toàn tài khoản": "Hãy sử dụng mật khẩu mạnh và kích hoạt xác thực hai yếu tố nếu có.",
    "Thông tin cá nhân chia sẻ với bên thứ ba": "Thông tin của bạn sẽ không được chia sẻ với bên thứ ba trừ khi có sự đồng ý của bạn.",
    "Kiểm soát ai xem báo cáo": "Có, bạn có thể chọn chế độ ẩn danh hoặc chỉ cho phép các phòng ban liên quan xem báo cáo.",
    "Báo cáo vấn đề bảo mật": "Vui lòng liên hệ bộ phận hỗ trợ hoặc gửi email để báo cáo các vấn đề về bảo mật.",
    "Yêu cầu quyền truy cập máy ảnh và vị trí": "Ứng dụng yêu cầu quyền này để giúp bạn tạo báo cáo chính xác và hiệu quả hơn.",
    "Xoá dữ liệu cá nhân": "Có, bạn có thể yêu cầu xóa dữ liệu cá nhân thông qua phần 'Cài đặt tài khoản'.",
    "Sử dụng dữ liệu cho quảng cáo": "Không, dữ liệu của bạn không được sử dụng cho mục đích quảng cáo.",
    "Người khác xem báo cáo của tôi": "Chỉ các phòng ban liên quan và người quản lý có quyền xem báo cáo của bạn.",
    "Bảo mật hai lớp": "Vào 'Cài đặt bảo mật' và chọn 'Bảo mật hai lớp' để kích hoạt.",
    "Liên hệ hỗ trợ khách hàng": "Bạn có thể liên hệ qua email, số điện thoại hoặc phần hỗ trợ trực tuyến trong ứng dụng.",
    "Gửi ý kiến đóng góp": "Bạn có thể gửi ý kiến đóng góp qua phần 'Phản hồi' trong cài đặt ứng dụng.",
    "Báo cáo lỗi ứng dụng": "Vào phần 'Phản hồi' và chọn 'Báo cáo lỗi'.",
    "Nâng cấp ứng dụng": "Kiểm tra bản cập nhật mới theo thông báo của hệ thống.",
    "Thời gian phản hồi yêu cầu": "Đội ngũ hỗ trợ sẽ phản hồi sớm nhất có thể, chậm nhất là trong vòng 24-48 giờ làm việc.",
    "Yêu cầu tính năng mới": "Vui lòng gửi yêu cầu tính năng mới qua phần 'Phản hồi'.",
    "Truy cập tài liệu hướng dẫn": "Vào phần 'Trợ giúp' hoặc 'Tài liệu' để tìm hướng dẫn.",
    "Ứng dụng có sẵn trên hệ điều hành khác": "Hiện tại, ứng dụng có định dạng APK file cho Android.",
    "Thử nghiệm tính năng mới": "Vui lòng đăng ký chương trình thử nghiệm qua phần 'Tham gia Beta' trong cài đặt.",
  },
  "en": {
    "Greeting" : "Hi, I'm a chat bot of RiskPrection. Which problem can I help you today ?",
    "Register a new account": "To register a new account, open the app and select 'Register'. Then fill in your personal information and follow the instructions.",
    "Forgot password": "Click on 'Forgot password' on the login page and enter your email. A link to reset your password will be sent to your email.",
    "Change password": "Go to 'Account Settings' and select 'Change Password'. Enter your current password and the new password, then confirm the change.",
    "Use account on multiple devices": "Yes, you can use your account on multiple devices as long as you log in with the same account.",
    "Did not receive verification code": "Ensure you have entered the correct phone number or email. If the issue persists, check your network connection and try again.",
    "Delete account": "Go to 'Account Settings' and select 'Delete Account'. Note that this action is irreversible and will delete all your data.",
    "Update personal information": "Go to 'Account Settings' and select 'Edit Personal Information'. You can update details like your name, email, and phone number.",
    "Cannot log in to my account": "Check if you have entered the correct login details. If not, try resetting your password or contact customer support.",
    "Log in using social media": "Yes, you can log in using your Google or Facebook account if supported by the app.",
    "Account locked": "Please contact customer support for further details and to request unlocking your account.",
    "Create a risk report": "Select 'Create Report' from the main menu, then follow the steps to enter information and add images if needed.",
    "Take photo or video when creating report": "Yes, the app allows you to take photos and record videos to illustrate the risk situation.",
    "Edit a submitted report": "Once submitted, reports cannot be edited. However, you can create a new report to update the information.",
    "Where is the risk report sent": "Reports are automatically sent to the relevant department based on the content and severity of the risk.",
    "Submit anonymous risk report": "Yes, you can choose the anonymous mode when creating a report if you do not want to disclose your identity.",
    "Classify risk severity levels": "The app provides options to classify risks based on your company's safety standards.",
    "View submitted reports": "Go to 'Report History' to view the reports you have submitted.",
    "Update report status": "After submitting a report, you will receive notifications when the report status changes.",
    "Limit on number of reports": "There is no limit to the number of reports you can submit.",
    "Notifications when report processed": "Yes, you will receive notifications when your report is reviewed and processed.",
    "Accumulate reward points": "You can accumulate reward points by creating risk reports, giving feedback, and participating in app activities.",
    "Redeem reward points": "Reward points can be redeemed for various gifts or benefits depending on the ongoing program.",
    "Check received reward points": "Reward points will appear on your profile, and you will receive notifications whenever points are added.",
    "Reward points expiration": "Yes, some reward points may expire. Check the 'Reward Points' section for details.",
    "Transfer reward points to others": "Currently, reward points cannot be transferred.",
    "Actions to earn reward points": "You can earn points by creating reports, providing feedback, and joining events.",
    "Join events to earn points": "Check the 'Events' section in the app for promotions and how to participate.",
    "Lose points if report rejected": "No, you will not lose points if your report is rejected.",
    "Reward points affect rank": "Yes, the accumulated points can affect your rank and benefits in the app.",
    "Reward points history": "Go to the 'Reward Points' section in your profile to view your history.",
    "User data security": "Yes, the app uses modern security measures to protect user data.",
    "Keep my account safe": "Use a strong password and enable two-factor authentication if available. Also, do not share your login information.",
    "Personal data shared with third parties": "Your information will not be shared with third parties unless you consent to it.",
    "Control who views my reports": "Yes, you can choose anonymous mode or allow only relevant departments to view your reports.",
    "Report security issues": "Please contact customer support or send an email to report any security issues.",
    "App requesting camera and location access": "The app requires these permissions to help you create accurate and effective reports.",
    "Request to delete personal data": "Yes, you can request to delete your personal data through the 'Account Settings' section.",
    "Use my data for advertising": "No, your data is not used for advertising purposes.",
    "Others viewing my reports": "Only relevant departments and authorized personnel can view your reports.",
    "Enable two-factor authentication": "Go to 'Security Settings' and select 'Two-Factor Authentication' to enable it.",
    "Contact customer support": "You can contact support via email, phone, or the in-app support section.",
    "Send feedback about the app": "You can send feedback through the 'Feedback' section in the app settings.",
    "Report app issues": "Go to the 'Feedback' section and select 'Report Issue'.",
    "Upgrade the app": "Check for new updates as notified by the system.",
    "Time for support to respond": "Support will respond as soon as possible, typically within 24-48 business hours.",
    "Request new features": "Please send feature requests through the 'Feedback' section.",
    "Access usage guide": "Go to the 'Help' or 'Documents' section to find usage guides.",
    "App available on other platforms": "Currently, the app is available as an APK file for Android.",
    "Test new features": "Sign up for the beta program through the 'Join Beta' section in settings.",
  },
  "ru": {
    "Привет" : "Привет. Я всегда рядом. Какая у вас проблема ?",
    "Регистрация нового аккаунта": "Чтобы зарегистрировать новый аккаунт, откройте приложение и выберите 'Регистрация'. Затем заполните личную информацию и следуйте инструкциям.",
    "Забыл пароль": "Нажмите 'Забыли пароль' на странице входа и введите свою электронную почту. Ссылка для сброса пароля будет отправлена на ваш email.",
    "Изменить пароль": "Перейдите в 'Настройки аккаунта' и выберите 'Изменить пароль'. Введите текущий пароль и новый, затем подтвердите изменение.",
    "Использовать аккаунт на нескольких устройствах": "Да, вы можете использовать свой аккаунт на нескольких устройствах, если войдете с тем же аккаунтом.",
    "Не получил код подтверждения": "Убедитесь, что вы ввели правильный номер телефона или email. Если проблема сохраняется, проверьте подключение к сети и попробуйте снова.",
    "Удалить аккаунт": "Перейдите в 'Настройки аккаунта' и выберите 'Удалить аккаунт'. Обратите внимание, что это действие необратимо и приведет к удалению всех ваших данных.",
    "Обновить личную информацию": "Перейдите в 'Настройки аккаунта' и выберите 'Редактировать личные данные'. Вы можете обновить такие данные, как имя, email и номер телефона.",
    "Не могу войти в аккаунт": "Проверьте правильность введенных данных. Если не получается, попробуйте сбросить пароль или обратитесь в службу поддержки.",
    "Вход через соцсети": "Да, вы можете войти через Google или Facebook, если приложение поддерживает такую функцию.",
    "Аккаунт заблокирован": "Свяжитесь со службой поддержки для получения дополнительной информации и запроса на разблокировку аккаунта.",
    "Создать отчет о риске": "Выберите 'Создать отчет' в главном меню, затем следуйте инструкциям для ввода информации и добавления изображений (при необходимости).",
    "Сделать фото или видео для отчета": "Да, приложение позволяет делать фото и записывать видео для иллюстрации ситуации.",
    "Редактировать отправленный отчет": "После отправки отчет нельзя редактировать. Однако вы можете создать новый отчет, чтобы обновить информацию.",
    "Куда отправляется отчет о риске": "Отчеты автоматически отправляются в соответствующий отдел в зависимости от содержания и степени риска.",
    "Отчет о риске анонимно": "Да, вы можете выбрать анонимный режим при создании отчета, если не хотите раскрывать свою личность.",
    "Классификация уровней риска": "Приложение предоставляет опции для классификации рисков на основе стандартов безопасности вашей компании.",
    "Просмотр отправленных отчетов": "Перейдите в 'История отчетов', чтобы просмотреть отправленные вами отчеты.",
    "Обновить статус отчета": "После отправки отчета вы получите уведомления при изменении его статуса.",
    "Лимит количества отчетов": "Ограничений на количество отчетов нет.",
    "Уведомления об обработке отчета": "Да, вы получите уведомления, когда ваш отчет будет рассмотрен и обработан.",
    "Накопить бонусные баллы": "Вы можете накапливать бонусные баллы, создавая отчеты, оставляя отзывы и участвуя в активностях приложения.",
    "Обменять бонусные баллы": "Бонусные баллы можно обменять на различные подарки или привилегии в зависимости от текущей программы.",
    "Проверить полученные бонусы": "Бонусные баллы будут отображены в вашем профиле, и вы получите уведомления при их начислении.",
    "Срок действия бонусных баллов": "Да, некоторые бонусные баллы могут иметь срок действия. Проверьте раздел 'Бонусные баллы' для подробностей.",
    "Передать бонусные баллы другим": "В настоящее время передача бонусных баллов недоступна.",
    "Действия для получения баллов": "Вы можете получать баллы, создавая отчеты, оставляя отзывы и участвуя в событиях.",
    "Участвовать в событиях для получения баллов": "Проверьте раздел 'События' в приложении, чтобы узнать о промоакциях и способах участия.",
    "Потеря баллов, если отчет отклонен": "Нет, вы не потеряете баллы, если ваш отчет отклонен.",
    "Бонусные баллы влияют на уровень": "Да, накопленные баллы могут влиять на ваш уровень и привилегии в приложении.",
    "История бонусных баллов": "Перейдите в раздел 'Бонусные баллы' в вашем профиле, чтобы посмотреть историю.",
    "Безопасность данных пользователя": "Да, приложение использует современные меры безопасности для защиты данных пользователей.",
    "Защита аккаунта": "Используйте надежный пароль и включите двухфакторную аутентификацию, если доступно. Не делитесь своими данными для входа.",
    "Личные данные передаются третьим лицам": "Ваши данные не передаются третьим лицам без вашего согласия.",
    "Кто может просматривать мои отчеты": "Вы можете выбрать анонимный режим или разрешить доступ только соответствующим отделам.",
    "Сообщить о проблемах с безопасностью": "Пожалуйста, свяжитесь со службой поддержки или отправьте email для сообщения о проблемах с безопасностью.",
    "Почему приложению нужен доступ к камере и местоположению": "Приложение требует эти разрешения для создания точных и эффективных отчетов.",
    "Удалить личные данные": "Да, вы можете запросить удаление личных данных через раздел 'Настройки аккаунта'.",
    "Используются ли мои данные для рекламы": "Нет, ваши данные не используются в рекламных целях.",
    "Кто может видеть мои отчеты": "Только соответствующие отделы и авторизованный персонал могут просматривать ваши отчеты.",
    "Включить двухфакторную аутентификацию": "Перейдите в 'Настройки безопасности' и выберите 'Двухфакторная аутентификация' для активации.",
    "Связаться с клиентской поддержкой": "Вы можете связаться с поддержкой через email, телефон или раздел помощи в приложении.",
    "Отправить отзыв о приложении": "Вы можете отправить отзыв через раздел 'Обратная связь' в настройках приложения.",
    "Сообщить об ошибке приложения": "Перейдите в раздел 'Обратная связь' и выберите 'Сообщить об ошибке'.",
    "Обновить приложение": "Проверьте наличие обновлений в уведомлениях системы.",
    "Время ответа поддержки": "Служба поддержки ответит как можно скорее, обычно в течение 24-48 рабочих часов.",
    "Запросить новые функции": "Пожалуйста, отправьте запрос на добавление функции через раздел 'Обратная связь'.",
    "Получить руководство по использованию": "Перейдите в раздел 'Помощь' или 'Документы', чтобы найти руководство по использованию.",
    "Приложение доступно на других платформах": "В настоящее время приложение доступно в формате APK для Android.",
    "Тестировать новые функции": "Зарегистрируйтесь в программе тестирования через раздел 'Бета-версия' в настройках.",
  },
};
